import { CertificateField, OutputSettings } from './types';

export const SYSTEM_FONTS = [
  { name: 'Inter', category: 'Sans-serif' },
  { name: 'Roboto', category: 'Sans-serif' },
  { name: 'Open Sans', category: 'Sans-serif' },
  { name: 'Montserrat', category: 'Sans-serif' },
  { name: 'Poppins', category: 'Sans-serif' },
  { name: 'Arial', category: 'Sans-serif' },
  { name: 'Helvetica', category: 'Sans-serif' },
  { name: 'Times New Roman', category: 'Serif' },
  { name: 'Georgia', category: 'Serif' },
  { name: 'Playfair Display', category: 'Serif' },
  { name: 'Merriweather', category: 'Serif' },
  { name: 'Cinzel', category: 'Serif' },
  { name: 'Great Vibes', category: 'Cursive / Script' },
  { name: 'Dancing Script', category: 'Cursive / Script' },
  { name: 'Courier New', category: 'Monospace' },
];

export const DEFAULT_OUTPUT_SETTINGS: OutputSettings = {
  format: 'png',
  quality: 0.95,
  filenamePattern: 'Certificate_{recipient_name}',
  zipFilename: 'CES_Certificates',
};

export const DEFAULT_FIELDS: CertificateField[] = [
  {
    id: 'field-name',
    label: 'Recipient Name',
    fieldKey: 'recipient_name',
    defaultValue: 'Alexander Hamilton',
    x: 15,
    y: 42,
    width: 70,
    height: 12,
    fontFamily: 'Montserrat',
    fontSize: 54,
    fontWeight: 700,
    fontStyle: 'normal',
    textColor: '#1a365d',
    textAlign: 'center',
    verticalAlign: 'middle',
    letterSpacing: 1.5,
    lineHeight: 1.2,
    textTransform: 'uppercase',
    textDecoration: 'none',
    multiLine: false,
    wrapMode: 'word',
    overflowBehavior: 'shrink',
    zIndex: 1,
    locked: false,
    visible: true,
    required: true,
  },
  {
    id: 'field-event',
    label: 'Event Name',
    fieldKey: 'event_name',
    defaultValue: 'Annual Technical Symposium & Hackathon 2026',
    x: 20,
    y: 56,
    width: 60,
    height: 8,
    fontFamily: 'Roboto',
    fontSize: 26,
    fontWeight: 600,
    fontStyle: 'normal',
    textColor: '#2b6cb0',
    textAlign: 'center',
    verticalAlign: 'middle',
    letterSpacing: 0.5,
    lineHeight: 1.3,
    textTransform: 'none',
    textDecoration: 'none',
    multiLine: true,
    wrapMode: 'word',
    overflowBehavior: 'shrink',
    zIndex: 2,
    locked: false,
    visible: true,
    required: false,
  },
  {
    id: 'field-date',
    label: 'Date',
    fieldKey: 'date',
    defaultValue: 'September 11, 2026',
    x: 12,
    y: 78,
    width: 28,
    height: 6,
    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: 400,
    fontStyle: 'normal',
    textColor: '#4a5568',
    textAlign: 'center',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    textTransform: 'none',
    textDecoration: 'none',
    multiLine: false,
    wrapMode: 'none',
    overflowBehavior: 'clip',
    zIndex: 3,
    locked: false,
    visible: true,
    required: false,
  },
  {
    id: 'field-cert-id',
    label: 'Certificate ID',
    fieldKey: 'certificate_id',
    defaultValue: 'CES-2026-CERT-001',
    x: 60,
    y: 78,
    width: 28,
    height: 6,
    fontFamily: 'Courier New',
    fontSize: 16,
    fontWeight: 600,
    fontStyle: 'normal',
    textColor: '#718096',
    textAlign: 'center',
    verticalAlign: 'middle',
    letterSpacing: 1,
    lineHeight: 1.2,
    textTransform: 'uppercase',
    textDecoration: 'none',
    multiLine: false,
    wrapMode: 'none',
    overflowBehavior: 'clip',
    zIndex: 4,
    locked: false,
    visible: true,
    required: false,
  },
];

export const MAX_SAFE_BATCH_SIZE = 5000;
export const BATCH_CHUNK_SIZE = 25; // Process in chunks of 25 to yield to event loop and manage memory
